#!/bin/sh

# Set Laptop Wake Time to 2am
# If the machine is a laptop, do some laptop-specific things
IS_LAPTOP=`/usr/sbin/system_profiler SPHardwareDataType | grep "Model Name" | grep "Book"`
if [ "$IS_LAPTOP" != "" ]; then
	# Laptops turn on at 1 AM, Shut back down at 4 AM to build back charge,
	# and Shutdown for the day at 6 PM.
	sudo pmset repeat wakeorpoweron MTWRF 01:00:00 shutdown MTWRFSU 04:00:00 shutdown MTWRFSU 18:00:00
else
	# Other Devices (Desktops) Run Later
	sudo pmset repeat wakeorpoweron MTWRF 05:00:00 shutdown MTWRFSU 18:00:00
fi

exit 0
